
mail.host = sandbox.smtp.mailtrap.io
mail.port = 2525
mail.username = 4c537e80c4c705
mail.password = 2cf60560891a12
app.mail =  orginfo.findabook@gmail.com
app.name = FindABook
app.url = http://localhost:8080/findabook_war/